### ISSUE TITLE
Last todos

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/production-docker#1]
### Please describe the feature you would like to see implemented.

Hey,

Since Shopware 6.5 extensions are allowed to run `composer` while installation. This will change on runtime the vendor folder so the current docker image cannot be used in a cluster system or with Shopware updates anymore.

The new image is just a base image containing PHP + Webserver. The Dockerfile in your project should build Shopware with your extensions and copy it into `/var/www/html`. In this way we can work again with cluster/multiple same containers.

I have created an example project [here](https://github.com/shyim/shopware/tree/main/example-project) and looking for feedback

Open tasks

- [x] Add JWT as Environment Variable
- [x] Provide Symfony Flex Recipe for overall configuration
- [x] Add docs
- [ ] Example Repo + GitHub Action

**Comment by lutek** [comment]
GitLab CI with its own Docker registry.

**Comment by shyim** [comment]
Is there an explicit reason why you prefer the web server in the container? 🤔

**Comment by lutek** [comment]
No, just convenience. I'm about to switch from my typical stack Debian VM + nginx + php-fpm to Docker Swarm based shops. Just suggesting nginx instead of caddy

**Comment by shyim** [comment]
I guess what would be okay, to build to kind of "flavours" one image with caddy and one with nginx

**Comment by shyim** [comment]
here is the example repo https://github.com/shyim/example-shopware-docker-project
